Torch mlir visualizer
ljfitz/mlir-xten pull request #1
Opened 2022-01-13 23:33 UTC by jcamacho1234

Merge all Visualizer code with main branch here.

2022-01-14 16:34 UTC, JRUMacDev reviewed
The code changes seem good to me. One question - why are the two tests in test/Conversion/ATenToXTen showing as additions? There two tests were already upstreamed. Perhaps I am just misunderstanding what the PR is showing?

2022-01-14 18:15 UTC, ljfitz requested changes
Given the verbosity of the target schema, the code looks well put together. I've added a few specific comments, pretty much all style and readability issues.

Most mlir upsteam projects require the use of `clang-format` and you should consider it too. `clang-format -i lib/Transform/ATenVisualGraph.cpp` will format it in place for you.

 I do think it misses a test that checks, for the smallest possible example, the full output. Then the other tests can focus on the parts that are unique to them. From the name and `CHECK` I understood the purpose of most tests, but not `test/Transform/ATenVisualGraph/tiny_yolo_v2_block.mlir`.

2022-01-17 08:38 UTC, ljfitz requested changes
Thanks for the changes @jcamacho1234. I was very happy that most of my comments could be marked as `Resolved`. The only one of significance remaining is to improve `test/Transform/ATenVisualGraph/tiny_yolo_v2_block.mlir` to make it clear what it is testing, either by providing a more thorough set of `CHECK` lines or add a comment to explain the key aspect that the single `CHECK-LABEL` covers.

2022-01-19 17:40 UTC, ljfitz requested changes

2022-01-19 17:40 UTC, ljfitz commented on test/Transform/ATenVisualGraph/tiny_yolo_v2_block.mlir
> +// CHECK-LABEL:     {
the use of https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-label-directive everywhere looks odd and that you really just want `CHECK:`. Could you check?

2022-01-20 07:28 UTC, ljfitz approved these changes

2022-05-17 11:24 UTC, ljfitz commented
I understand that this was effectively merged via upstream.

2022-05-17 11:24 UTC, closed without merging